# -*- coding: utf-8 -*-

# Form implementation generated from reading app file 'form.app'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1198, 744)
        self.verticalLayoutWidget = QtWidgets.QWidget(Widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 19, 1151, 711))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.task_txt = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.task_txt.setObjectName("task_txt")
        self.horizontalLayout_5.addWidget(self.task_txt)
        self.formulas = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.formulas.setObjectName("formulas")
        self.horizontalLayout_5.addWidget(self.formulas)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.task_selection = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.task_selection.setObjectName("task_selection")
        self.task_selection.addItem("")
        self.task_selection.addItem("")
        self.task_selection.addItem("")
        self.verticalLayout_4.addWidget(self.task_selection)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.data_1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.data_1.setObjectName("data_1")
        self.horizontalLayout_2.addWidget(self.data_1)
        self.data_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.data_2.setObjectName("data_2")
        self.horizontalLayout_2.addWidget(self.data_2)
        self.calculate = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.calculate.setObjectName("calculate")
        self.horizontalLayout_2.addWidget(self.calculate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.answer = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.answer.setObjectName("answer")
        self.horizontalLayout_3.addWidget(self.answer)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.task_txt.setText(_translate("Widget", "TextLabel"))
        self.formulas.setText(_translate("Widget", "TextLabel"))
        self.task_selection.setItemText(0, _translate("Widget", "Задача №1"))
        self.task_selection.setItemText(1, _translate("Widget", "Задача №2"))
        self.task_selection.setItemText(2, _translate("Widget", "Задача №4"))
        self.calculate.setText(_translate("Widget", "Вычислить"))
        self.answer.setText(_translate("Widget", "TextLabel"))

